### ISSUE TITLE
Where to give feedback?

### ISSUE THREAD

**Issue by privefl** [teuder/rcpp4everyone_en#5]
You say "I would greatly appreciate it if you kindly give me any feedback on this document."
I'm currently reading your document and I will use some part for my Advanced R course.
Where do you want to get some feedback?

**Comment by teuder** [comment]
Thank you for the comment.
I was expecting the following feedbacks

- corection of grammatical mistakes or those of difficult to read sectenses.
- corection of mistakes in Rcpp.
- Pointing out of the fix due to Rcpp version upgrade

I would appreciate if you could edit the .md file and send me a pull request.
But if you are not familier with git, I would welcome you to describe feed backs in this issue.

**Comment by privefl** [comment]
I'm familiar with Git but Fork+PR is sometimes too much for just one small change, I think.
Just one comment then, you say that `return` is mandatory, but it's not when the return type is `void`.

**Comment by teuder** [comment]
I fixed the point. Thanks!
